-- CreateEnum
CREATE TYPE "RegistrationStatus" AS ENUM ('REGISTER_START', 'EMAIL_SENT', 'EMAIL_VERIFIED', 'STRIPE_CUSTOMER_CREATED', 'PAYMENT_METHOD_ATTACHED', 'SUBSCRIPTION_CREATED', 'PAYMENT_SUCCEEDED', 'AVATAR_JOB_ENQUEUED', 'AVATAR_READY', 'PROFILE_COMPLETED', 'ACTIVE', 'ROLLBACK_PENDING', 'CLAIMS_REVOKED', 'FIRESTORE_CLEANED', 'STRIPE_REFUNDED', 'ROLLBACK_DONE');

-- AlterTable
ALTER TABLE "profiles" ADD COLUMN     "regMeta" JSONB,
ADD COLUMN     "regRetryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "registrationStatus" "RegistrationStatus" NOT NULL DEFAULT 'REGISTER_START';

-- CreateIndex
CREATE INDEX "profiles_registrationStatus_idx" ON "profiles"("registrationStatus");
