// pages/_app.tsx
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Geist, Geist_Mono } from 'next/font/google'
import '../styles/globals.css'
import Navbar from '../components/Navbar'

// Load Google fonts and assign to CSS variables
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* Meta tags and title for all pages */}
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Apply font variables and antialiasing globally */}
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Persistent site navbar */}
        <Navbar />

        {/* Page content */}
        <Component {...pageProps} />
      </div>
    </>
  )
}