// pages/_app.tsx
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Geist, Geist_Mono } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import Navbar from '../components/Navbar'
import { AuthProvider } from '../hooks/useFirebaseNextAuth'

// Load Google fonts and assign to CSS variables
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function MyApp({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <AuthProvider>              {/* 🔁 Bridge Firebase → Next-Auth */}
      <SessionProvider session={session}>
        <Head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Persistent site header */}
          <Navbar />

          {/* Page content */}
          <Component {...pageProps} />
        </div>
      </SessionProvider>
    </AuthProvider>

  )
}
